apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ortelius-www-canary
spec:
  ports:
  - name: www
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ortelius-www
    tier: backend
status:
  loadBalancer: {}
