DockerRepo: quay.io/ortelius/website
DockerTag: main-v9.0.0.334-gcd73761
affinity: {}
fullnameOverride: ""
image: 1645370/ortelius-www:2022-09-03--28-28
ingress:
  annotations: {}
  className: ""
  enabled: true
  host: ortelius.io
  path: /
  pathType: Prefix
  tls: []
nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}
service:
  port: 80
  type: ClusterIP
tolerations: []
